### ISSUE TITLE
Investigation: Move AWS ECS Services to NAT

### ISSUE THREAD

**Issue by derekbelrose** [OA-PASS/Operations#1]
Situation: AWS limits, by default, the number of IPv4 addresses to 50 for FARGATE launched services for the account to 50.  Currently, each PASS environment uses 9 IP addresses and that will grow as we add new services.  PASS is managed by the Library's AWS account so this would have an effect on library resources.

I suggest that we take a few hours to research creating an AWS NAT Gateway and altering the gateway for the subnets so that it points to the NAT gateway instead.  We only need 1 NAT Gateway for all of PASS, so this would require only 5 IP addresses for all 3 environments (Ops server, NAT gateway, 3 load balancers).  This is far better than the current 28 IP addresses that are required for PASS as built.

Here's what I currently anticipate having to do:

1) Create a NAT gateway
2) Reassign the gateway setting for the subnets that the ECS services are assigned
3) TEST.

I would like to take 2-3 hours to test this.  I could start tomorrow morning and have an answer on the feasibility of this change by 1pm.

**Comment by derekbelrose** [comment]
I have spent some time working on this tonight and I will need to move a couple more services around in terms of networking. The individual containers work right now, but things like the load balancer cannot talk to them.

I disabled NAT for now and am able to get to Test again.  I will continue tomorrow.

**Comment by derekbelrose** [comment]
Ok, I believe this is a viable solution.  Tonight, I was able to make test work with only private IP addresses assigned to the ECS tasks.  It requires the following to work:

Common Shared Infrastructure:
1 EIP
1 NAT Gateway

Each Environment Requires the following to be created:
2x Subnets assigned to the Default Gateway (public subnets)

Each load balancer will need to be modified to sit on the public subnets
The two existing subnets will need to be assigned to the NAT Gateway
Security groups need to be adjusted for the Shibboleth container and DSpace container

All in all, the work required to get this done has been completed. I would like to spend a little more time to double check all security groups.  Once that is completed, I would like someone to poke at Test.

**Comment by derekbelrose** [comment]
I have all security groups updated except for one.  The security group for the PSQL database that Fedora uses is being stubborn. 

Everything else seems to work.

**Comment by derekbelrose** [comment]
@htpvu I think we can say this is something that can be done.  How should we proceed?

**Comment by htpvu** [comment]
@derekbelrose i'd make this an investigation ticket. We'd make a new ticket for the implementation. 

Before closing this one though, could you give information about the following:
- how long it would take
- what risks are involved if things don't go as plan, what are the worst case scenarios?
- whether there would be any effect on developers, users, 
- anticipated outage time.

**Comment by derekbelrose** [comment]
Hanh,

I don’t know about “investigation” tickets.

To answer your questions:
10 minutes Best case scenario
No risks involved, we’d just disable “NAT” and things go back as they were
No effects on developers, users except for the 10 minutes downtime
10 minute downtime expected.


On Feb 15, 2019, at 10:26 AM, Hanh Vu <notifications@github.com<mailto:notifications@github.com>> wrote:


@derekbelrose<https://github.com/derekbelrose> i'd make this an investigation ticket. We'd make a new ticket for the implementation.

Before closing this one though, could you give information about the following:

  *   how long it would take
  *   what risks are involved if things don't go as plan, what are the worst case scenarios?
  *   whether there would be any effect on developers, users,
  *   anticipated outage time.

**Comment by htpvu** [comment]
@derekbelrose this was the investigation ticket. It accounts for your time spent looking into how feasible the proposal was. 

Now that you're done with that feasibility study, this can be close. Implementation ticket has been created https://github.com/OA-PASS/Operations/issues/4
