### ISSUE TITLE
Deploy to PROD new pass-authz image

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/Operations#13]
image tag is `oapass/authz:0.4.3-3.2`

**Comment by derekbelrose** [comment]
@htpvu would it be possible to deploy this tonight, Tuesday April 9th at midnight?

**Comment by htpvu** [comment]
@derekbelrose, could you remind me what the down time for this would be?

We know that there is at least one researcher trying to submit articles in to pass at this time, so I’d like to avoid interrupting that as much as possible.

**Comment by derekbelrose** [comment]
We are looking at about 10 minutes to bring it up.

Sent from my iPhone

On Apr 9, 2019, at 12:03 PM, Hanh Vu <notifications@github.com<mailto:notifications@github.com>> wrote:


@derekbelrose<https://github.com/derekbelrose>, could you remind me what the down time for this would be?

We know that there is at least one researcher trying to submit articles in to pass at this time, so I’d like to avoid interrupting that as much as possible.

**Comment by htpvu** [comment]
@derekbelrose the article submission we were expecting had been summitted. if you could let me know when you'd like to do this deployment with 1-2 days heads up, I'll let the other folks know, then we can go ahead with the deployment. 

OR you can send out an email to the oapass-announce group with the headsup (downtime +duration, that'll work too.

thank you.

**Comment by derekbelrose** [comment]
Let’s shoot for Tuesday night midnight.

On Apr 12, 2019, at 17:11, Hanh Vu <notifications@github.com<mailto:notifications@github.com>> wrote:


@derekbelrose<https://github.com/derekbelrose> the article submission we were expecting had been summitted. if you could let me know when you'd like to do this deployment with 1-2 days heads up, I'll let the other folks know, then we can go ahead with the deployment.

OR you can send out an email to the oapass-announce group with the headsup (downtime +duration, that'll work too.

thank you.

**Comment by derekbelrose** [comment]
I will send out an email tonight.

Sent from my iPhone

On Apr 12, 2019, at 5:12 PM, Hanh Vu <notifications@github.com<mailto:notifications@github.com>> wrote:


@derekbelrose<https://github.com/derekbelrose> the article submission we were expecting had been summitted. if you could let me know when you'd like to do this deployment with 1-2 days heads up, I'll let the other folks know, then we can go ahead with the deployment.

OR you can send out an email to the oapass-announce group with the headsup (downtime +duration, that'll work too.

thank you.
