### ISSUE TITLE
Deploy CMF to DEV 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/Operations#16]
Configuration of ENV VARs for all services can be found here https://github.com/OA-PASS/pass-docker#configuring-the-docker-images 

Order of these steps should be followed as listed:
Pre data migration:
- [x] Put PASS in Under Maintenance mode.  (Derek)
- [x] Update data in Elastic Search to esconfig-3.4: (index copy dance) (Elliot)
- [x] Deploy updated Fedora - `oapass/fcrepo:4.7.5-3.4-1@sha256:56faf95a9753f2548665de0154888221a7c02ae2158489d08ec5499ed7ceb3fd`
- [x] Deploy updated Indexer - `oapass/indexer:0.0.18-3.4-1@sha256:3375ea702e0a1c7a5e0e7e06635d28e49af436aeb1c3d88a03d4cb494d7b40bf`

Data migration:
- [x] Add schema links to existing Repositories - 1hr  (Elliot)
- [x] Run journal loader/converter utility to convert ISSNs and add new journals - 0.5 day  (Jim)
- [x] Run metadata blob converter utility on existing deposits - 0.5 day (Elliot)

Post data-migration:
- [x] Deploy DOI service - *new service* - `oapass/doi-service:version1.0.0@sha256:a82a1b60b4bae17b9a5628ed3d65501000d576ef3ba6bc3ffe4cbf9138eba82d`
- [x] Deploy Ember - `oapass/ember:20190514-ab7204f@sha256:86356247d5e57e5f551ff8b8648317d65333dcd8f135051bef9e4bf275f3817a`
- [x] Deploy policy service - *new service* - `oapass/policy-service:v0.1.2@sha256:b361bc7dd9d366465f7683052e038e5ec93ef77a48e69176590c84044ce7d804`
- [x] Deploy the schema service - *new service* - `oapass/schema-service:v0.3.1@sha256:9276b5262e964f19ee0bc9be9eedb82c237349afe6d934ba84b5a152bab44bc5`
- [x] Deploy the deposit service - `oapass/deposit-pass-docker:1.0.0-3.4-SNAPSHOT@sha256:299e8c6bb8a861e2147f13d728fee898e61d2be5554ae405d8ddb29b50419fe8`
- [x] Turn PASS back on? (Derek)
- [ ] Verify that services are running properly.

**Comment by derekbelrose** [comment]
Ok, policy service SHOULD be running ok now.  Hopefully some developers can poke at it on Monday morning and we can close this off.
