### ISSUE TITLE
dev instance - null value problem

### ISSUE THREAD

**Issue by jrmartino** [OA-PASS/Operations#17]
steps to reproduce:
1. log in
2. new submission
3. enter doi (doi service populates form) or journal info
4. select grant.
5. tap next
![Screenshot from 2019-06-03 08-06-55](https://user-images.githubusercontent.com/310967/58800847-f87dcb80-85d6-11e9-8fa0-54f9a7e1a60a.png)

**Comment by htpvu** [comment]
Request URL looks something like this `https://dev.pass.library.jhu.edu/policyservice/policies?submission=https://dev.pass.library.jhu.edu/fcrepo/rest/submissions/e2/de/e1/e7/e2dee1e7-bc30-4236-9f99-3db383bb4e48`

**Comment by derekbelrose** [comment]
That looks right. Unfortunately, the error handling and even logging in the Policy Service is lacking at the moment. I’ll see if i can dig through the source and see what it might be failing on.

Hopefully, someone will be able to track this down quickly.


Sent from my iPad

On Jun 3, 2019, at 10:17 AM, Hanh Vu <notifications@github.com<mailto:notifications@github.com>> wrote:


Request URL looks something like this https://dev.pass.library.jhu.edu/policyservice/policies?submission=https://dev.pass.library.jhu.edu/fcrepo/rest/submissions/e2/de/e1/e7/e2dee1e7-bc30-4236-9f99-3db383bb4e48

**Comment by jrmartino** [comment]
one thing to check is that all the environment variables are correctly set: it looks for PASS_EXTERNAL_FEDORA_BASEURL, PASS_FEDORA_BASEURL, PASS_FEDORA_USER, PASS_FEDORA_PASSWORD,  POLICY_SERVICE_PORT

On 6/3/19 11:21 AM, Derek Belrose wrote:
That looks right. Unfortunately, the error handling and even logging in the Policy Service is lacking at the moment. I’ll see if i can dig through the source and see what it might be failing on.

Hopefully, someone will be able to track this down quickly.


Sent from my iPad

On Jun 3, 2019, at 10:17 AM, Hanh Vu <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Request URL looks something like this https://dev.pass.library.jhu.edu/policyservice/policies?submission=https://dev.pass.library.jhu.edu/fcrepo/rest/submissions/e2/de/e1/e7/e2dee1e7-bc30-4236-9f99-3db383bb4e48

**Comment by derekbelrose** [comment]
Yes, i’ve done that. NULL is a useless error and we need to fix that part.

The logging doesn’t say anything and the error is literally null.

PASS_EXTERNAL_FEDORA_BASEURL    https://dev.pass.library.jhu.edu/fcrepo/rest/
PASS_FEDORA_BASEURL     http://fcrepo-dev.pass.local:8080/fcrepo/rest
PASS_FEDORA_PASSWORD    moo
PASS_FEDORA_USER        fedoraAdmin
POLICY_FILE     aws.json
POLICY_SERVICE_PORT     8088

Sent from my iPad

On Jun 3, 2019, at 11:54 AM, Jim Martino <notifications@github.com<mailto:notifications@github.com>> wrote:

one thing to check is that all the environment variables are correctly set: it looks for PASS_EXTERNAL_FEDORA_BASEURL, PASS_FEDORA_BASEURL, PASS_FEDORA_USER, PASS_FEDORA_PASSWORD, POLICY_SERVICE_PORT

On 6/3/19 11:21 AM, Derek Belrose wrote:
That looks right. Unfortunately, the error handling and even logging in the Policy Service is lacking at the moment. I’ll see if i can dig through the source and see what it might be failing on.

Hopefully, someone will be able to track this down quickly.


Sent from my iPad

On Jun 3, 2019, at 10:17 AM, Hanh Vu <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Request URL looks something like this https://dev.pass.library.jhu.edu/policyservice/policies?submission=https://dev.pass.library.jhu.edu/fcrepo/rest/submissions/e2/de/e1/e7/e2dee1e7-bc30-4236-9f99-3db383bb4e48

**Comment by derekbelrose** [comment]
To check logs:

https://login.johnshopkins.edu/aws and log in with your JHED
Click Services, Type CloudWatch and click the CloudWatch entry
Click Logs on the left hand vertical list
Click pass-dev
Click on the first entry for dev/policy

The environment variables are listed in https://github.com/OA-PASS/Operations/issues/17#issuecomment-498354174

If you have ssh access to ops.pass.jhu.edu, you can test URLS that are passed to the policy server. I have confirmed that the submission exists.

**Comment by htpvu** [comment]
resolved.
