### ISSUE TITLE
Request to Schema service by the UI is met with 500 error code

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/Operations#19]
Steps to produce:
- Open the google dev tools window,  Open the network tab
- start a new submission, step through the workflow until you reach an empty metadata form on step 4
- observe the network traffic information in the network tab.  
<img width="1381" alt="Screen Shot 2019-06-04 at 11 48 35 PM" src="https://user-images.githubusercontent.com/11050142/58929077-4b649980-8723-11e9-90fd-8b1deee4589c.png">

**Comment by derekbelrose** [comment]
The external URL was pointing to HTTP not HTTPS. Once changed, testers reported that it was working.
