### ISSUE TITLE
Updating PASS production instance with new infrastructure

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/Operations#3]
When: January 10th 00:00 - 02:00
Services Affected: ALL

Description of Actions being taken: 

We plan to bring PASS Production up to date with the architecture that Demo and Test have deployed.  This will break the single monolithic ECS Task Definition into smaller, more manageable Task Definitions. 

All of the work is done in ECS.  There is no data that will be modified during this migration.  Terraform, the deployment and infrastructure orchestration software that we use for PASS, will delete the existing ECS Service, Task Definition and Tasks.  It will then create new ECS Services, several new Task definitions and then spin up all the Tasks.

The benefit of this move is that we are no longer running one monolithic Task Definition that needs to be recreated with each minute change.  The problem that exists right now is that if we choose to update the Ember Application image, it requires restarting fcrepo, indexer, deposit service, etc.  This means that an infrastructure wide interruption happens for just an HTML update.

Going forward, most components of PASS will have their own Task Definition and Service.  This means that updating the Ember image will only affect the Ember service.  Other components, such as deposit service, will continue running in the background doing what they do.

We have done this twice before with little to no issues. Any issues are introduced (usually network permissions, which are easily mitigated by me) by this change and can be quickly sorted out.  The ultimate fallback is to revert, but I cannot see this happening.

**Comment by derekbelrose** [comment]
Adding @jgara for comments, if needed

**Comment by derekbelrose** [comment]
Preparatory Steps:
- [ ] Migrate settings file for production to SSM Parameters
- [ ] Sync up Terraform definitions for production
- [ ] Note changes that have to be made in Proxy configuration
- [ ] Take note of potential DNS conflicts and remediate.

**Comment by birkland** [comment]
Does this mean that the individual task can get their own size "instance" (for lack of a better word)?  i.e. one of these configurations: https://aws.amazon.com/fargate/pricing/

**Comment by derekbelrose** [comment]
Yes, in fact that's how we adjusted Shibboleth to give it more RAM this week.

In Test and Demo, we're already using this feature in order to "right size" tasks.

**Comment by derekbelrose** [comment]
SSM Parameters have been configured.  We are set for Saturday night.

**Comment by derekbelrose** [comment]
Migration has begun

**Comment by derekbelrose** [comment]
Migration is completed.  The process took about 10 minutes.  I have successfully created a test entry that was deposited into JScholarship.

I have asked Drew to remove that entry in JScholarship.
