### ISSUE TITLE
Issue with ElasticSearch using wrong URLs 

### ISSUE THREAD

**Issue by htpvu** [OA-PASS/Operations#7]
@derekbelrose could you please add some details on this ticket?

**Comment by derekbelrose** [comment]
With the old Amazon ECS setup, each docker container was available via "localhost".  This has changed now that we're breaking out docker containers into their own services.

The URIs in Elasticsearch all start with http://localhost:8080 for fcrepo.  This is incorrect.  My plan is to change the URI's from http://localhost:8080 to http://fcrepo-(test|demo|prod).pass.local:8080.  Each @type in Elasticsearch is different, they collect different elements.  This requires specially crafting a Painless Elasticsearch script for each type.  

All of this work is already done.

**Comment by derekbelrose** [comment]
Update: The URI's being rewritten was successful.  Unfortunately that wasn't the only problem, the demo environment had a bunch of duplicates from bad runs prior to this.

I have, with the help of @markpatton and @jrmartino, created what I need to bootstrap a minimal environment and run the NIHMS ETL and COEUS loaders.

**Comment by derekbelrose** [comment]
This has been fixed in the test environment.

**Comment by htpvu** [comment]
Has been fixed in production as well, per Derek.
